export const ActionTypes = {
    SET_USER: "SET_USER",
    USER_LOGIN: "USER_LOGIN",
    USER_LOGOUT: "USER_LOGOUT",
    USER_SIGNUP: "USER_SIGNUP",
    ERROR: "ERROR",
    OPEN_MODAL: "OPEN_MODAL",
    CLOSE_MODAL: "CLOSE_MODAL",
    OPEN_MENU: "OPEN_MENU",
    CLOSE_MENU: "CLOSE_MENU",
    OPEN_LOGIN_FORM: "OPEN_LOGIN_FORM",
    CLOSE_LOGIN_FORM: "CLOSE_LOGIN_FORM",
    OPEN_SIGNUP_FORM: "OPEN_SIGNUP_FORM",
    CLOSE_SIGNUP_FORM: "CLOSE_SIGNUP_FORM",
    CLOSE_LOGOUT_FORM: "CLOSE_LOGOUT_FORM",
    OPEN_LOGOUT_FORM: "OPEN_LOGOUT_FORM"
}