export const ActionTypes = {
    SET_USER: "SET_USER",
    USER_LOGIN: "USER_LOGIN",
    USER_LOGOUT: "USER_LOGOUT",
    USER_SIGNUP: "USER_SIGNUP",
    ERROR: "ERROR",
    OPEN_MODAL: "OPEN_MODAL",
    CLOSE_MODAL: "CLOSE_MODAL"
}